config/routes.rb
Rails.application.routes.draw do

  post "/search" ,to: "proyects#search" , as: 'search'
  get "/search" ,to: "proyects#index"

  resources :proyect_files
  resources :categories
  resources :responsibles
  resources :responsibilities
  resources :proyects
  devise_for :users 
 
 
  get "/dashboard" ,to: "welcome#dashboard"

  
  get "/cusers" ,to: "users#index" , as: 'users'
  get "/cusers/:id" ,to: "users#show" , as: 'user'
  get "/cusers/:id/edit" ,to: "users#edit" , as: 'edit_user'
  delete "cusers/:id" , to: "users#destroy"
  patch "/cusers/:id" , to: "users#update"

  put "/proyects/:id/finish_it", to: "proyects#finish_it"
  get 'welcome/index'
  root 'proyects#index'

end

app/views/partials/_aside.html.erb
<aside class="col-md-3 hidden-xs hidden-sm" >  <!-- ocultar en dispositivos peq -->
	<h4>Categories</h4>
	<div class="list-group">
	<% @categories.each do |category|  %>
		<%= aside_link_to category.name, category %>
	<% end %>

	</div>
	<h4>Recent Proyects</h4>
	<div class="list-group">
		<% @proyectaside.each do |pro_aside|  %>

			<%= aside_link_to (" <h4 class=\" list-group-item-heading\"> #{ pro_aside.title} </h4> <p class=\" list-group-intem-text\"> #{truncate(pro_aside.body,lenght:90) } </p>").html_safe, pro_aside %>
			
		<% end %>
	</div>	
	<h4>Currents Responsibles</h4>
	<div class="list-group">
		<% @responsibles.each do |responsible|  %>

			<%= aside_link_to (" <h4 class=\" list-group-item-heading\"> #{responsible.first_name} </h4><p  class=\" list-group-intem-text\"> #{responsible.email} </p>").html_safe, responsible ,style:" " %>
		<% end %>
	</div>	
</aside>

app/views/partials/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-6">
				<p>AlphaLab</p>
			</div>
			<div class="col-xs-6">
				<ul class="list-inline text-right">
				
					<li><a href="#">Contact</a></li>
					
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/partials/_navigation.html.erb
	<nav class="navbar navbar-static-default navbar-inverse navbar-static-top">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle toggle-left collapsed" data-toggle="collapse" data-target="#alphacollapse"v>
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "AlphaLab" , root_path ,class:"navbar-brand"%>
			
	    </div>
   		<button type="button" class="navbar-toggle navbar-btn toggle-right" data-toggle="sidebar" data-target=".sidebar-right">
          <span class="glyphicon glyphicon-user white" aria-hidden="true"></span>
        </button>
	   
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="alphacollapse">
	     
	     <%= form_tag( search_path, class: 'navbar-form navbar-left' ) do %>
	        <div class="form-group">
	          <input type="text" class="form-control" name="searcher[textsearch]" placeholder="Search">
	           <select name="searcher[field]"  class="form-control">
	              <option value="title">Title</option>
	              <option value="body">Body</option>
	              <option value="category">Category</option>
	              <option value="responsible">Responsible</option>
              </select>
	        </div>
          	<button type="submit" class="btn btn-primary">
 				<span class="glyphicon glyphicon-search"></span>
 			</button>
	      <% end %>
	      
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container -->
	</nav>


	<div class="col-xs-7 col-sm-2 col-md-2  sidebar sidebar-right sidebar-animate">
      <ul class="nav nav-pills nav-stacked">
        
        <div class="placeholder">
          <h4 class="text-center">Signed as:</h4>
         
			<% if user_signed_in? %>
			 <p class="text-center">
         	 	<span class="text-muted"> <%= current_user.email %></span>
         	 </p>
         	<%else %>
				<span class="text-muted">Visitor</span>
          	<%end %>
        </div>
        <hr>
        <li class="divider" role="separator"></li>
        <% if user_signed_in? %>
			 <% if current_user.is_editor? %>
				<li class="<%= 'active' if params[:controller] == 'categories' %>" ><%= link_to"Categories", categories_path %></li>
				<li class="<%= 'active' if params[:controller] == 'responsibles' %>"><%= link_to"Responsibles", responsibles_path %></li>
				<li ><%= sidebar_link_to "Add Proyects" , new_proyect_path %></li>
		
				<li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to"Configuser", users_path %></li>
				
			 <% end %>
        	
			<li ><%= sidebar_link_to "Change Password" , edit_user_registration_path %></li>
			<li><%= link_to "Sign out", destroy_user_session_path, method: :delete, id: "exit", data: { confirm: 'Are you sure?' } %></li>
		<% else %>
			<li >
				<%= sidebar_link_to "Sign In", new_user_session_path  %>
			</li>
			<li >
				<%= sidebar_link_to "Sign up", new_user_registration_path  %>
			</li>
		<% end %>
       
       
      </ul>
      
    </div>

    <section class="jumbotron">
		<div class="container">
			<h1>AlphaLab</h1>
			<p>Repositories</p>
		</div>
	</section>
	 