config/routes.rb
Rails.application.routes.draw do

  post "/search" ,to: "proyects#search" , as: 'search'
  get "/search" ,to: "proyects#index"

  resources :proyect_files
  resources :categories
  resources :responsibles
  resources :responsibilities
  resources :proyects
  devise_for :users 
 
 
  get "/dashboard" ,to: "welcome#dashboard"

  
  get "/cusers" ,to: "users#index" , as: 'users'
  get "/cusers/:id" ,to: "users#show" , as: 'user'
  get "/cusers/:id/edit" ,to: "users#edit" , as: 'edit_user'
  delete "cusers/:id" , to: "users#destroy"
  patch "/cusers/:id" , to: "users#update"

  put "/proyects/:id/finish_it", to: "proyects#finish_it"
  get 'welcome/index'
  root 'proyects#index'

end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  belongs_to :proyect
  belongs_to :responsible
  validates_presence_of :proyect
  validates_presence_of :responsible
end

app/controllers/responsibilities_controller.rb
class ResponsibilitiesController < ApplicationController
  before_action :set_responsibility, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin! 
  
 
  def index
    @responsibilities = Responsibility.all
  end

  def show
  end

  def new
    @responsibility = Responsibility.new
  end

  def edit
  end

  def create
    @responsibility = Responsibility.new(responsibility_params)

    respond_to do |format|
      if @responsibility.save
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully created.' }
        format.json { render :show, status: :created, location: @responsibility }
      else
        format.html { render :new }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @responsibility.update(responsibility_params)
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsibility }
      else
        format.html { render :edit }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @responsibility.destroy
    respond_to do |format|
      format.html { redirect_to responsibilities_url, notice: 'Responsibility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_responsibility
      @responsibility = Responsibility.find(params[:id])
    end

    def responsibility_params
      params.require(:responsibility).permit(:user_id, :proyect_id)
    end
end

app/helpers/responsibilities_helper.rb
module ResponsibilitiesHelper
end

app/views/responsibilities/_form.html.erb
<%= form_for(@responsibility) do |f| %>
  <% if @responsibility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responsibility.errors.count, "error") %> prohibited this responsibility from being saved:</h2>

      <ul>
      <% @responsibility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

   <p>
     <strong> <%= responsibility.responsible.first_name %></strong>
   </p>


    <%= f.label :responsible_id %><br>
    <%= f.text_field :responsible_id %>
  </div>

  <div class="field">
    <%= f.label :proyect_id %><br>
    <%= f.text_field :proyect_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responsibilities/edit.html.erb
<h1>Editing Responsibility</h1>

<%= render 'form' %>

<%= link_to 'Show', @responsibility %> |
<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Responsibilities</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibilities.each do |responsibility| %>
      <tr>
        <td><%= responsibility.responsible.first_name %></td>
        <td><%= responsibility.proyect.title %></td>
        <td><%= link_to 'Show', responsibility %></td>
        <td><%= link_to 'Edit', edit_responsibility_path(responsibility) %></td>
        <td><%= link_to 'Destroy', responsibility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responsibility', new_responsibility_path %>

app/views/responsibilities/new.html.erb
<h1>New Responsibility</h1>

<%= render 'form' %>

<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @responsibility.responsible %>
</p>

<p>
  <strong>Proyect:</strong>
  <%= @responsibility.proyect %>
</p>

<%= link_to 'Edit', edit_responsibility_path(@responsibility) %> |
<%= link_to 'Back', responsibilities_path %>