config/routes.rb
Rails.application.routes.draw do

  post "/search" ,to: "proyects#search" , as: 'search'
  get "/search" ,to: "proyects#index"

  resources :proyect_files
  resources :categories
  resources :responsibles
  resources :responsibilities
  resources :proyects
  devise_for :users 
 
 
  get "/dashboard" ,to: "welcome#dashboard"

  
  get "/cusers" ,to: "users#index" , as: 'users'
  get "/cusers/:id" ,to: "users#show" , as: 'user'
  get "/cusers/:id/edit" ,to: "users#edit" , as: 'edit_user'
  delete "cusers/:id" , to: "users#destroy"
  patch "/cusers/:id" , to: "users#update"

  put "/proyects/:id/finish_it", to: "proyects#finish_it"
  get 'welcome/index'
  root 'proyects#index'

end

app/models/responsible.rb
class Responsible < ActiveRecord::Base
	has_many :responsibilities
	has_many :proyects, through: :responsibilities

	validates :first_name, presence: true,length:{minimum:4}, uniqueness: true 
	validates :last_name, presence: true, length:{minimum:4}
	validates :address, presence: true, length:{minimum:8}
	validates :email , presence: true, length:{minimum:4}, uniqueness: true 
	validates :photo, presence: true

	has_attached_file :photo, styles:{ medium: "800x600", thumb:"640x480", mini:"320x240"}  #decirle al modelo q tiene attach de imagen
	validates_attachment_content_type :photo , content_type: /\Aimage\/.*\Z/

	after_create :save_responsibilities
	after_update :save_updateresponsibilities

	def assignproyect=(value)
			@assignproyect= value
	end

	private

	def save_responsibilities # guarda las categioas en has categori
		
		unless @assignproyect.nil? #para los markup 
			@assignproyect.each do |assignproyect_id|
				Responsibility.create(proyect_id: assignproyect_id, responsible_id: self.id)
			end
		end
	end
	def save_updateresponsibilities # guarda las categioas en has categori
		#raise @assignproyect.to_yaml

		unless @assignproyect.nil? #para los markup 
			#raise self.proyects.first.to_yaml
			self.proyects.clear

			@assignproyect.each do |assignproyect_id|
				Responsibility.create(proyect_id: assignproyect_id, responsible_id: self.id)
			end
		end
	end

end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
    
  before_action :authenticate_editor! , only:[:index,:edit,:new,:create,:update]
  before_action :authenticate_admin!, only:[ :new,:edit,:create,:update,:destroy]
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]
  
  before_action :set_proyect , only: [:new,:edit]
 
  def index
    @responsibles = Responsible.paginate(page: params[:page],per_page:5)
  end

  
  def show
  end

 
  def new
    @responsible = Responsible.new
  end

 
  def edit
   
  end
  
  def create
    @responsible = Responsible.new(responsible_params)
    @responsible.assignproyect = params[:proyects]
    #raise params.to_yaml
    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsible was successfully created.' }
        format.json { render :show, status: :created, location: @responsible }
      else
        format.html { render :new }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    @responsible.assignproyect = params[:proyects]
    respond_to do |format|
    
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsible was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsible }
      else
        format.html { render :edit }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url, notice: 'Responsible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_responsible
      @responsible = Responsible.find(params[:id])
    end

    def set_proyect
      @proyects = Proyect.all
    end

   
    def responsible_params
      params.require(:responsible).permit(:first_name, :last_name, :email, :address, :photo,:proyects)
    end
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/responsibles/_form.html.erb
<%= form_for(@responsible) do |f| %>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-md-7 col-md-offset-2">
    <% if @responsible.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@responsible.errors.count, "error") %> prohibited this responsible from being saved:</h2>

        <ul>
          <% @responsible.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="" style="padding-left:0">
       <%= f.label "Photo", class: "control-label" %>
        <div class="">
          <div class="thumbnail" style="overflow:hidden;">
            <div id="target">
              <%= image_tag @responsible.photo.url( :thumb ), class: "img-responsive" %>
            </div>
            <br>
            <%= f.file_field :photo, class: "image" %>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name , class:"form-control"%>
    </div>
   <div class="form-group">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name,class:"form-control" %>
    </div>

   <div class="form-group">
      <%= f.label :email  %><br>
      <%= f.text_field :email,class:"form-control" %>
    </div>
   <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_area :address ,class:"form-control"%>
    </div>
    <div class=" ">
       <% if user_signed_in? %>
           <% if current_user.is_admin? %>
            <div class="field">
              <%= f.label "Responsiblities" %><br>
                <% if @proyects.present? %>

                     <%= f.select :proyects, options_for_select(@proyects.collect{|proyect| [proyect.title,proyect.id]}, @responsible.proyects.map{|proyect| proyect.id}), {}, {:multiple => "multiple", :class=>'form-control selectpicker', 'data-live-search'=>true , 'data-style'=>'btn-success'} %>
                 
                <% else %>
                 <p>No Responsibilities</p>
                 <%= link_to  "Add New" , new_responsible_path%>
                <%end%>
           </div>
          <% end %>
      <% end %>
   </div>
    <div class=" col-xs-12 text-center" style="margin-top: 1em;">
      <%= f.submit class:"btn btn-primary" %>
       <%= link_to 'Back', responsibles_path, class:"btn btn-warning" %>
    </div>
  </div>
</div>
<% end %>

app/views/responsibles/edit.html.erb
<article class="  col-md-9 clearfix" > 
	<h1>Editing Responsible</h1>
	<%= render 'form' %>
</article>

app/views/responsibles/index.html.erb
 <article class="  col-md-9 clearfix" >
    
    <div class="text-center">
         <h2>Listing Responsibles</h2>
    </div>
     <div class="text-center">
      <%= will_paginate @proyects%>
    </div>
    <div class="col-xs-12">
      <p>
       <%= link_to 'New Responsible', new_responsible_path , class:"btn btn-primary" %>
      </p>
    </div>
   <% @responsibles.each do |responsible| %>
    <div class="row post">
        <div class="col-xs-12 col-sm-4">
           <img class="img-thumbnail" src="<%= responsible.photo.url(:thumb)%>" alt="<%= responsible.photo_file_name %>">
        </div>

        <div class="col-xs-12 col-sm-8">
            <h2 class="post-title">
             <%= link_to responsible.first_name, responsible %> 
            </h2>
          
            <p>
              <strong>Member Since: </strong>
              <em>
                <%= responsible.created_at%>
              </em>
           
            </p>
            <p class="text-justify">
              <strong>Address: </strong><%=truncate(responsible.address,lenght:60) %>
            </p>
            
        </div>
     
        <div class="col-xs-12 " style=" margin-top: 1em;">
          <p>
            <strong>Current Projects (<%= responsible.proyects.count %>)</strong> 
            <% responsible.proyects.each do | rproject |%>
                - <%= link_to rproject.title, rproject %>
            <% end %>
          </p>
        </div>
         <div class="col-xs-12 text-center">
              <%= link_to "<button class=\"btn btn-success\"> <span class=\" glyphicon glyphicon-edit\"></button> </span>".html_safe , edit_responsible_path(responsible) , alt:"Edit" , title:"Edit" %>
              <% if user_signed_in? %>
                <% if current_user.is_admin? %>
                 <%= link_to  "<button class=\"btn btn-danger\"> <span class=\" glyphicon glyphicon-trash\"></button> </span>".html_safe  , responsible, alt:"Destroy" , title:"Destroy", method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%> 
              <%end%> 
         </div>
      </div>
   <% end %>
   <div class="text-center">
      <%= will_paginate @proyects%>
    </div>
</article>

app/views/responsibles/new.html.erb
<div class="col-xs-12 text-center">
	<h1>New Responsible</h1>
</div>

<%= render 'form' %>

app/views/responsibles/show.html.erb
 <article class=" post col-md-9 clearfix" >
  <% unless @responsible.photo.url.nil? %>
    <img class="thumbnail img-medium" src="<%= @responsible.photo.url(:thumb)%>" alt="<%= @responsible.photo_file_name %>">
  <% end %>
  <div class="row">
    <div class="col-xs-12  col-sd-10 col-md-12  ">
      <h1 class="text-center"> <%= @responsible.first_name %> <%= @responsible.last_name %> </h1>
      <p class="text-justify text-left">
        <strong>Member Since:</strong>
        <%= @responsible.created_at %>
      </p>
      <p class="text-justify text-left">
        <strong>Email:</strong>
        <%= @responsible.email %>
      </p>
      <div class="text-justify center-block">
        <strong>Address </strong>
        <%=truncate(@responsible.address,lenght:60) %>
      </div>
    </div> 
     <div class="col-xs-12 " style=" margin-top: 1em;">
          <p>
            <strong>Current Projects (<%= @responsible.proyects.count %>)</strong>
            <% @responsible.proyects.each do | rproject |%>
                - <%= link_to rproject.title, rproject %>
            <% end %>
          </p>
    </div> 
    <div class=" actions col-xs-12 text-center">
       
        <% if user_signed_in? %>
           <% if current_user.is_editor? %>
           <%= link_to "Edit", edit_responsible_path(@responsible), class:"btn btn-success underline" %> 
            <%end%>
        <%end%>
         <%= link_to "Back", responsibles_path, class:"btn btn-warning underline" %> 
    </div>
  </div>
</article>