config/routes.rb
Rails.application.routes.draw do

  post "/search" ,to: "proyects#search" , as: 'search'
  get "/search" ,to: "proyects#index"

  resources :proyect_files
  resources :categories
  resources :responsibles
  resources :responsibilities
  resources :proyects
  devise_for :users 
 
 
  get "/dashboard" ,to: "welcome#dashboard"

  
  get "/cusers" ,to: "users#index" , as: 'users'
  get "/cusers/:id" ,to: "users#show" , as: 'user'
  get "/cusers/:id/edit" ,to: "users#edit" , as: 'edit_user'
  delete "cusers/:id" , to: "users#destroy"
  patch "/cusers/:id" , to: "users#update"

  put "/proyects/:id/finish_it", to: "proyects#finish_it"
  get 'welcome/index'
  root 'proyects#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	
	has_many :has_categories
	has_many :proyects, through: :has_categories
	validates :name , presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_editor! , only: [:new,:index ,:edit, :update]
  before_action :authenticate_admin!, only: [:destroy]


  def index
    #@categories = Category.all
  end

  def show
     @cate = @category.proyects.paginate(page: params[:page],per_page:5)
  end
  
  def new
    @category = Category.new
  end
  
  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
 
 <div class="row">
   <div class="col-xs-12">
     <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <table class="table table-striped ">
      <thead>
        <th width="35%" class="text-center"> <%= f.label :name %></th>
        <th width="35%" class="text-center">  <%= f.label :color %><br></th>
        <th width="30%" class="text-center">Actions</th>
      </thead>
      <tbody>
        <td class="text-center"> 
          <div class="field">
            <%= f.text_field :name %>
          </div>
        </td>
        <td class="text-center">
          <div class="field">
           <%= f.color_field :color %>
          </div>
        </td>
        <td class="text-center">
          <div class="  ">
            <%= f.submit class:"btn btn-primary" %>
          </div>
        </td>
      </tbody>
    </table>
   </div>
 </div>
 
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>
<div class="actions col-xs-12 text-center">
	<%= link_to 'Back', categories_path ,class:'btn btn-warning'%>
</div>

app/views/categories/index.html.erb
<article class="  col-md-9 clearfix" >
  <div class="row">
  <h1>Listing Categories</h1>

    <div class="col-xs-12">
          <a href="<%= new_category_path %>" class="btn btn-primary" alt="Add Category " title="Add Category">
            <span class="glyphicon glyphicon-edit"></span>&nbsp; Add Category 
          </a>
          
    </div> 

    <div class="col-xs-12 " style="margin-top: 1em;">
       <table class="table table-striped">
          <thead>
            <tr>
              <th width="30%">Name</th>
              <th width="30%">Color</th>
              <th width="40%" colspan="3" class="text-center">Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td style="color: <%= category.color %>;"><%= category.color %></td>
                <td class="text-center"><%= link_to "<span class=\"blue glyphicon glyphicon-sunglasses\"></span>".html_safe , category  %></td>
                <td class="text-center"><%= link_to "<span class=\"green glyphicon glyphicon-edit\"></span>".html_safe, edit_category_path(category) %></td>
                <% if current_user.is_admin? %>
                  <td class="text-center"><%= link_to  "<span class=\"red glyphicon glyphicon-trash\"></span>".html_safe, category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                 <%end%>  
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
     
  </div>
</article>  

app/views/categories/new.html.erb
<article class="post  col-md-9 clearfix" >
	<h1>New Category</h1>
	<%= render 'form' %>
	<div class="col-xs-12 text-center">
		<%= link_to 'Back', categories_path , class:"btn btn-warning"%>
	</div>
</article >

app/views/categories/show.html.erb
<article class="  col-md-9 clearfix" >
	<div class="col-xs-12 text-center margin-botom">
		<h1 style="color: <%= @category.color %>;"> <%= @category.name %></h1>
	</div>
	
	<%= render @cate %>
	<div class="text-center">
		<%= will_paginate @cate%>
	</div>
</article>
	